### ISSUE TITLE
Questions about data augmentation

### ISSUE THREAD

**Issue by hyf015** [happinesslz/EPNet#1]
Hi, thank you for sharing the code!
I have a small question about the data augmentation process. I wonder during the flipping and rotation of the lidar data, do you perform similar augmentation on the image? I think it is hard to flip the image along the forward direction...

**Comment by happinesslz** [comment]
@hyf015  For LI-Fusion,  we don't  perform any data augmentations on the image.

**Comment by hyf015** [comment]
Thank you for the reply!
