### ISSUE TITLE
Table 1. Ablation experiments on the KITTI val dataset

### ISSUE THREAD

**Issue by jlqzzz** [happinesslz/EPNet#14]
I am confused about the ablation experiment in Table 1.

If I understand it correctly, when LI-Fusion and CE are removed, the network structure will become very similar to PointRCNN. But the performance of the first row in Table 1 is much lower than that of PointRCNN.  Why?

Paper: EPNet (without LI-Fusion and CE) 86.34, 77.52, 75.96
Code: EPNet (without LI-Fusion and CE) 88.76, 78.03, 76.20   (@R40)

Paper: PointRCNN 89.19, 78.85, 77.91
Code: PointRCNN 91.82, 80.66, 78.16  (@R40)

**Comment by happinesslz** [comment]
Our code is based on the official  implement [PointRCNN](https://github.com/sshaoshuai/PointRCNN)  . The only difference is that we run PointRCNN online instead of offline.
