### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by biancaAlexandru** [happinesslz/EPNet#15]
When trying to build the 3 libraries (pointnet, iou3d and roipoool3d) I have the same error with an invalid command for CUDA. Might it be from the version of the NVIDIA Toolkit?

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc -c src/ball_query_gpu.cu -o build\temp.win-amd64-3.6\Release\src/ball_query_gpu.obj -IC:\ProgramData\Anaconda3\envs\epnet\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\epnet\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\epnet\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\epnet\lib\site-packages\torch\include\THC "-IC:\Program Files\" -IC:\ProgramData\Anaconda3\envs\epnet\include -IC:\ProgramData\Anaconda3\envs\epnet\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc' failed: Invalid argument

**Comment by happinesslz** [comment]
@biancaAlexandru  Maybe you should run the code on Ubuntu16.04 rather than Windows.

**Comment by biancaAlexandru** [comment]
I could solve all the errors and build on Windows 10 after reinstalling all the packages to be compliant with the NVIDIA Toolkit 
https://pytorch.org/get-started/previous-versions/
