### ISSUE TITLE
I can't understand the function of cfg.RPN.USE_RGB

### ISSUE THREAD

**Issue by 304886938** [happinesslz/EPNet#16]
Hi! I'm learning EPNet recently, your job is great and it is very helpful to me.
I can't understand the function of cfg.RPN.USE_RGB. It doesn't appear in LI_Fusion_with_attention_use_ce_loss.yaml, but appear in other files. I guess cfg.RPN.USE_RGB is used to control whether to use image input.Am I right?
Thanks for your answer!

**Comment by happinesslz** [comment]
@304886938  Maybe the understanding is not so right.  In fact , we need not the  cfg.RPN.USE_RGB in this project. If you want to use the image, you cloud set [cfg.LI_FUSION.ENABLED](https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/lib/datasets/kitti_rcnn_dataset.py#L265) as True.

**Comment by 304886938** [comment]
Thank you very much for your answer !
