### ISSUE TITLE
Error loading KITTI data

### ISSUE THREAD

**Issue by biancaAlexandru** [happinesslz/EPNet#17]
When trying to run 'train_rcnn.py' I have the following KeyError from loading the images:
"train_functions.py", line 40, in model_fn
    img = torch.from_numpy(data['img']).cuda(non_blocking=True).float().permute((0, 3, 1, 2))
KeyError: 'img'
I checked the keys and there is no key for 'img'
The keys are: dict_keys(['sample_id', 'random_select', 'rgb', 'aug_method', 'pts_input', 'pts_rect', 'pts_features', 'rpn_cls_label', 'rpn_reg_label', 'gt_boxes3d'])

I looked into the code but I could not find a solution.
Thank you in advance

**Comment by happinesslz** [comment]
@biancaAlexandru  I run the code successfully. We load the 'img' in Line 355 of [kitti_rcnn_dataset.py](https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/lib/datasets/kitti_rcnn_dataset.py#L355).
