### ISSUE TITLE
About handling details

### ISSUE THREAD

**Issue by ZacharyZgw** [happinesslz/EPNet#18]
Hello, i have a question about image size. SUNRGBD have different image size. How you deal with them. Can you tell me the details. Thank you very much!

**Comment by XiwuChen** [comment]
We set a larger size, i.e. (544, 768), to ensure that each image is not cropped. 
```
img_mask = np.zeros((544, 768, 3), dtype = np.float32)
shape = img.shape
img_mask[:shape[0], :shape[1], :] = img
ret_dict['img'] = img_mask.transpose((2, 0, 1)).astype(np.float32)
```
This operation is similar to https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/lib/datasets/kitti_dataset.py#L54-L55, since images in the KITTI dataset also have different size.
