### ISSUE TITLE
TypeError: 'function' object is not subscriptable

### ISSUE THREAD

**Issue by niujiaxing** [happinesslz/EPNet#19]
hello,i have a question in EPNet\tools\kitti_object_eval_python\rotate_iou_cpu.py **line 329**
![image](https://user-images.githubusercontent.com/35755586/113800538-b9e46980-9789-11eb-8720-84935eed061d.png)
When I run the program, it prompts me that there is an error in this line。
TypeError: 'function' object is not subscriptable
I want to know what the [] after the function means and whether there is a problem with this usage。
thank u !

**Comment by XiwuChen** [comment]
Sorry for the late reply. I am also a freshman at numba. I guess [] used here is the configuration for the kernel function `rotate_iou_kernel_eval`, which points out how many blocks and threads per grid and block respectively. This is similar to <<<>>> used in CUDA. Now you have encountered this problem, I am worried whether you have installed numba correctly. 

You could open an issue in [traveller59/kitti-object-eval-python](https://github.com/traveller59/kitti-object-eval-python), If you have more questions about `rotate_iou_cpu.py`.

**Comment by niujiaxing** [comment]
Xiwu, thank u very much for u reply, I reinstalled numba and now this problem is solved. But I still have a question. When I verify the epoch, iou and acc are both 0. When I print the variables, I find that the tensor of seg_rusult is all 0. Do you know what the problem is?
![image](https://user-images.githubusercontent.com/35755586/114507898-5a44fd00-9c66-11eb-8220-f2789c2b6b9a.png)

**Comment by XiwuChen** [comment]
It is hard to detect problems from such little information you provided. I don't know how you get this output. I think you can first use our provided pre-trained model to test and then check whether this problem is caused by the training step or evaluation function.
