### ISSUE TITLE
Model input and output

### ISSUE THREAD

**Issue by niujiaxing** [happinesslz/EPNet#21]
https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/tools/eval_rcnn.py#L549
Hello author, I want to see the format of the model input and output print, if you have time,could you explain what these variables represent, thank you very much
[1.txt](https://github.com/happinesslz/EPNet/files/6316594/1.txt)

**Comment by happinesslz** [comment]
@niujiaxing 

input:
'pts_input': the input point cloud for Geometric Stream in  Two stream RPN.
'pts_origin_xy': the corresponding coordinates on the image from 3D point cloud to 2D image.
'img': the input image for Image Stream in Two stream RPN.

output:
'rpn_cls' and 'rpn_reg' : the classification and regression  in  Two stream RPN, respectively.
'backbone_xyz' and 'backbone_features': the coordinates and their corresponding features of point cloud, respectively.
'rois': the output 3D boxes in RPN stage, which will be used in RCNN stage.
'seg_result': the segmentation in Two stream RPN, which can be obtained from 'rpn_cls'.
'rcnn_cls' and 'rcnn_reg': the classification and regression  in  RCNN stage, respectively.
