### ISSUE TITLE
Two questions about the code

### ISSUE THREAD

**Issue by 304886938** [happinesslz/EPNet#22]
Hi! I'm learning EPNet recently, your job is great and it is very helpful to me.
I have two questions about the code.
1. In kitti_rcnn_dataset.py, I only find the point cloud has data augmentation but image has not data augmentation, can they align?
2. In kitti_rcnn_dataset.py, if cfg.LI_FUSION.ENABLED is true, I think point cloud and img are both  loaded by the method of self.get_rpn_with_li_fusion, and we don't need to use the method of self.get_rpn_sample, am I right?
Look forward to your answers! Thank you very much!

**Comment by XiwuChen** [comment]
1. The alignment is utilized before data augmentation and the original pixel coordinate of each point is kept. So they are still aligned.
2. Yes, you are right. We keep `self.get_rpn_sample` for ablation study.

**Comment by 304886938** [comment]
Thank you very, very much for your answer!!!
