### ISSUE TITLE
Question about the inferring time?

### ISSUE THREAD

**Issue by lihua213** [happinesslz/EPNet#4]
Thanks for your nice work. I have tested your code, I found it is very slow. However, you mentioned that the inferring speed is 10 FPS. Is it really 10 FPS?

**Comment by happinesslz** [comment]
@lihua213  Thanks for your attention. We test the code on Titan V, and  also modify the TEST.RPN_POST_NMS_TOP_N from  100 to 64 to speed up the inference in the [LI_Fusion_with_attention_use_ce_loss.yaml](https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/tools/cfgs/LI_Fusion_with_attention_use_ce_loss.yaml#L186) .

**Comment by lihua213** [comment]
> @lihua213 Thanks for your attention. We test the code on Titan V, and also modify the TEST.RPN_POST_NMS_TOP_N from 100 to 64 to speed up the inference in the [LI_Fusion_with_attention_use_ce_loss.yaml](https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/tools/cfgs/LI_Fusion_with_attention_use_ce_loss.yaml#L186) .

Thanks so much. BTW, could you share the multi-class version?

**Comment by happinesslz** [comment]
@lihua213  Sorry, due to my busy studies，I will support the multi-class version in the near future.
