### ISSUE TITLE
end-to-end training

### ISSUE THREAD

**Issue by linbaiwpi** [happinesslz/EPNet#5]
I noticed that during training, the **train_mode** is set to **rcnn_online**. It looks for me the authors choose train the rpn and rcnn networks end-to-end. Therefore, I am wondering why. Obviously, end-to-end training is easier but is it better than training in two steps?

**Comment by happinesslz** [comment]
@linbaiwpi  Thanks for your attention. Yes, we train the network end-to-end. Maybe you can obtain the better model in two steps. However, it's hard for us to select the RPN model for better adapting the  RCNN  stage in two steps, which brings many parameters and  a lot of uncertainty.  So I am not recommended for training in two steps.
