### ISSUE TITLE
"assert i == 2, '%d' % i" issue

### ISSUE THREAD

**Issue by linbaiwpi** [happinesslz/EPNet#6]
Hi when using my own dataset, I got the following assertion error. Could you explain why putting an assertion here?

> Traceback (most recent call last):
>   File "/lbai/EPNet6000/tools/train_rcnn.py", line 276, in <module>
>     lr_scheduler_each_iter = (cfg.TRAIN.OPTIMIZER == 'adam_onecycle')
>   File "/lbai/EPNet6000/tools/../tools/train_utils/train_utils.py", line 197, in train
>     loss, tb_dict, disp_dict = self._train_it(batch)
>   File "/lbai/EPNet6000/tools/../tools/train_utils/train_utils.py", line 130, in _train_it
>     loss, tb_dict, disp_dict = self.model_fn(self.model, batch)
>   File "/lbai/EPNet6000/tools/../lib/net/train_functions.py", line 50, in model_fn
>     ret_dict = model(input_data)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/lbai/EPNet6000/tools/../lib/net/point_rcnn.py", line 59, in forward
>     rois, roi_scores_raw = self.rpn.proposal_layer(rpn_scores_raw, rpn_reg, backbone_xyz)  # (B, M, 7)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/lbai/EPNet6000/tools/../lib/rpn/proposal_layer.py", line 47, in forward
>     order_single)
>   File "/lbai/EPNet6000/tools/../lib/rpn/proposal_layer.py", line 93, in distance_based_proposal
>     assert i == 2, '%d' % i
> AssertionError: 1
> 
> Process finished with exit code 1
>

**Comment by happinesslz** [comment]
@linbaiwpi  Maybe the error is from "dist_mask.sum() == 0",  please carefully check the line [dist_mask](https://github.com/happinesslz/EPNet/blob/0123c341243846aa3b412addcb9e2c07fd305237/lib/rpn/proposal_layer.py#L81)
