### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by xuntan97** [happinesslz/EPNet#7]
Hi,can I have your email or wechat. I have some question. thank you.

**Comment by happinesslz** [comment]
@xuntan97  Thanks for your attention. The email is zheliu1994@hust.edu.cn. Any question, please feel free to contact me

**Comment by xuntan97** [comment]
> @xuntan97 Thanks for your attention. The email is [zheliu1994@hust.edu.cn](mailto:zheliu1994@hust.edu.cn). Any question, please feel free to contact me

Hi. I sent you an email in Chinese, looking forward to your reply. Thank you.
