### ISSUE TITLE
bash run_eval_model.sh

### ISSUE THREAD

**Issue by liu52020** [happinesslz/EPNet#9]
I meet a question!help me!

![image](https://user-images.githubusercontent.com/73093990/105050140-6f1b5580-5aa8-11eb-9904-60b5cd67e559.png)

**Comment by liu52020** [comment]
when i run bash run_eval_model.sh , my server is always down.

**Comment by happinesslz** [comment]
@liu52020  I have not encountered a similar problem. Please check out your sever, and I think this problem is not cased by the code.
